# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 

image:
  repository: 
  tag: 
  pullPolicy: 

service:
  type: 
  port: 

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
