#Adding the coreos repo for helm
helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
#Create a k8s namespaces
kubectl create ns alerting
#install prometheus operator
helm install --name helm coreos/prometheus-operator --namespace alerting
#Provide the required access for prometheus instance
# ------------------------------------#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: alerting
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: alerting
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  namespace: alerting
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: alerting
# ------------------------------------#


