# ------------------- prometheus Service Account ------------------- #
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus-server
  name: prometheus-server
  namespace: monitoring  # namespace in which prometheus object is created.
---
# ------------------- Cluster Admin access  for prometheus------------------- #
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-server
  labels:
    app: prometheus-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: prometheus-server
  namespace: monitoring
